name: Build Microstation using Nuitka (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/*requirements.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -r dev-requirements.txt
      
      - name: Compile Resources
        run: |
          scripts/compile-ui.ps1
          Set-Alias -Name rcc -Value C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\site-packages\qt6_applications\Qt\bin\rcc.exe
          scripts/compile-icons.ps1
          Set-Alias -Name lrelease -Value C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\site-packages\qt6_applications\Qt\bin\lrelease.exe
          scripts/compile-langs.ps1
          scripts/compile-styles.ps1

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: microstation
          mode: onefile
          python-flag: |
            no_asserts
            no_docstrings
            -m
          prefer-source-code: true
          windows-console-mode: attach
          windows-icon-from-ico: microstation/icons/aperture.ico
          include-data-dir: |
            microstation/arduino/=arduino/
            microstation/external_styles/=external_styles/
            microstation/icons/=icons/
            microstation/langs/=langs/
            microstation/ui/=ui/
          include-data-files: |
            microstation/version.txt=version.txt
          enable-plugins: pyqt6

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
          include-hidden-files: true
